### PR TITLE
Plugsuit

### PR DESCRIPTION
**Pull request by janearc**
this is the merge-in of [plugsuit](https://github.com/janearc/plugsuit). it lays the groundwork for shared state, shared config, shared code, which was not possible in the "previous setup", wherein all code was self-contained and atomic. this can be considered a "redesign" of sorts, but also adds a lot of functionality in terms of debugging (which is useful on a project of this size), unit testing (which has been a long-standing issue) and should make the code generally more robust.

### CODE REVIEW

**Comment by janearc** [comment]
it looks like travis is asking for singleton, which doesn't seem to actually be requested in the tree.

**Comment by konklone** [comment]
FWIW, when I tried to run this locally (a couple hours ago), I also got told that `singleton` was required.

**Comment by janearc** [comment]
Yeah I am not sure why that is. Nobody is using it. I grepped through Sendak and didn't find it. If you can find it, I will definitely buy you a cookie. :)

**Comment by janearc** [comment]
(caveat: a couple things, like `deep-grep` *are* using `singleton`, but that should be handled in *those* packages)

**Pull request merged**
